version: '3.8'
services:
  fileserver:
    image: kyawthihadev/fileserver:main
    volumes:
      - /root/uploads:/usr/src/app/uploads
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always
