version: '3.8'
services:
  fileserver:
    image: kyawthihadev/fileserver:main
    volumes:
      - /root/uploads:/usr/src/app/uploads
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always
  static-file-server:
    container_name: static-file-server
    image: nginx:alpine
    restart: always
    ports:
      - 8800:8800
    volumes:
      - /root/uploads:/srv
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
