version: '3.8'
services:
  fileserver:
    container_name: fileserver
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 100M
