version: '3.8'
services:
  fileserver:
    container_name: fileserver
    build: .
    volumes:
      - ./uploads:/usr/src/app/uploads
    ports:
      - "8080:8080"
    env_file:
      - .env
    # restart: always 

